In [1]:
import numpy as np
import Layer

In [2]:
W = np.identity(4)
b = np.zeros(4).reshape(4,1)
W.shape, b.shape

((4, 4), (4, 1))

In [3]:
layer = Layer.Layer(4, 4, activation=False)
x = np.random.rand(4).reshape(1,4)
x

array([[0.73024608, 0.31931865, 0.74811571, 0.64501595]])

In [4]:
x.T.shape


(4, 1)

In [5]:
W = np.identity(4).reshape(4,4)
np.matmul(x, W)

array([[0.73024608, 0.31931865, 0.74811571, 0.64501595]])

In [6]:
def dxtanh(x):
    return 1 - np.tanh(x) ** 2

In [7]:
a = dxtanh(np.zeros(4).reshape(4,1))
a

array([[1.],
       [1.],
       [1.],
       [1.]])

In [8]:
a.reshape(4)

array([1., 1., 1., 1.])

In [9]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.zeros(16).reshape(4,4) + np.ones(4).reshape(1,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])